### ISSUE TITLE
Logo in the title bar 

### ISSUE THREAD

**Issue by anshgautam-github** [GameSphere-MultiPlayer/PACKABUNCHAS#12]
### 🎮 feature Request

![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/95379812/1394773b-3718-45ef-8434-970ff9399f5f)

In the title section, it would look much good if I put the logo of the game over there, it will give it a more of professional look.

### Point down the features

LOGO IN THE TITLE BAR

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by motuncoded** [comment]
Can I work on this issue?

**Comment by pandey079** [comment]
Please assign it to me under GSSOC'24

**Comment by iDhruv03** [comment]
I can work on this. Please assign me this issue

**Comment by Durgesh4993** [comment]
@motuncoded @pandey079 @iDhruv03 Please raise any other issue, i'll assign you 

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by motuncoded** [comment]
Ok

**Comment by jinamsancheti** [comment]
If not yet assigned can you assign me this issue under #gssoc'24
