### ISSUE TITLE
[New Feature]: Introduction of PACKABUNCHAS Homepage

### ISSUE THREAD

**Issue by Ayushvishwakarma04** [GameSphere-MultiPlayer/PACKABUNCHAS#17]
### 🎮 feature Request

feature logic and basic description:
We propose implementing a homepage specifically tailored for PACKABUNCHAS. This homepage will serve as a central point for players to access essential game information, interesting facts, and a leaderboard displaying top scores.

### Point down the features

feature points:
1. **Game Information Section:** The homepage will provide a brief overview of PACKABUNCHAS, including its gameplay mechanics, and key features. This section aims to give players a quick understanding of what the game entails and why it's worth playing.

2. **Fun Facts Segment:** Players will discover intriguing facts about PACKABUNCHAS, such as development insights and notable achievements. These fun facts add an element of surprise and entertainment for players, encouraging them to explore the game further.

3. **High Scores Leaderboard:** A prominent feature of the homepage will be the leaderboard showcasing the highest scores achieved by players. This leaderboard fosters healthy competition among players, motivating them to improve their skills and strive for the top spots.

4. **Main Game Page Section:** An additional section will provide a direct link to the main game page, allowing players to seamlessly transition to the full game experience. This ensures that players have easy access to the game itself, where they can dive deeper into gameplay and engage.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task for GSSoC 24.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
