### ISSUE TITLE
[Enhancement]: The first page can be improved.

### ISSUE THREAD

**Issue by anshika-gupta21** [GameSphere-MultiPlayer/PACKABUNCHAS#19]
Hello, I am Anshika, GSSoC'24 contributor. The first page of the application starts the game by clicking anywhere on the screen.

![Screenshot 2024-05-13 160102](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/124676798/a823f889-75dd-4ea4-b0f1-db3453832bac)

 It can be enhanced by adding a start button in the middle (that space looks empty too) and only starting when the button is clicked. This would lead to more concise and professional gaming experience. 

Kindly assign me this issue and I'll get to it right now.

**Comment by anshika-gupta21** [comment]
I mean whenever we click anywhere on the screen, including the yellow part, the game starts. Instead, there should be a particular button on the central rectangular screen for starting the game. We can make a new START button in the centre vacant space. The game should start only on clicking on the particular button, instead of the whole screen.

**Comment by ritikaguptaa** [comment]
Hey @Durgesh4993 Please assign this task to me.

**Comment by 143divya** [comment]
Hey @Durgesh4993 Please assign this task to me
