### ISSUE TITLE
There is no CONTRIBUTING.md file in repository 

### ISSUE THREAD

**Issue by Braj-01** [GameSphere-MultiPlayer/PACKABUNCHAS#21]
### Describe your question or ask for support.❓

The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Braj-01** [comment]
Can you please assign me this task so that I can add it for user perspective.

**Comment by alishasingh06** [comment]
please assign me this task

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/98798977/6d586e5f-98d2-4f25-b023-bdb385ef7c82)

**Comment by Durgesh4993** [comment]
@Braj-01 @alishasingh06 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
