### ISSUE TITLE
Missing CONTRIBUTION.md file in the Repository

### ISSUE THREAD

**Issue by deekshithapalla** [GameSphere-MultiPlayer/PACKABUNCHAS#22]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by LAKSHYA1509** [comment]
Hi Contribute.MD Is a crucial file that contains all the potential information on how to create your own pull request and for new beginners regarding this project and therefore with a knack of content writing
I would really love working on that and this includes all the contribution guidelines and all the standards of coding with the procedures of how to submit a pull request thus it is very important to have a contributing.MD file and therefore,
I would be very very happy if you would assign this task to me I will create all the necessary informations with that contributing dot md file with all the git bash commands and other things so I would really request that can you please assign this task to me under the GSSOC 2024.
