### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by hasmithagunda123** [GameSphere-MultiPlayer/PACKABUNCHAS#24]
### Describe the bug ✍️

I want to add requirements section to the project assign me

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@hasmithagunda123 could you please explain more what you want to do

**Comment by hasmithagunda123** [comment]
actually it is not a bug but its a documentation on the requirements like what versions we need to have inorder to perform and what are the software s and necessities for the project

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
