### ISSUE TITLE
Missing Code of Conduct File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [GameSphere-MultiPlayer/PACKABUNCHAS#3]
### Describe the bug ✍️

Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behavior, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Kindly assign me this issue, so i can work towards it under GSSOC 24

### Provide step by step information reproduce the bug 📄

We need to create a Code of Conduct file and integrate it into our repository. This file should outline expected behaviors, consequences for violating the Code of Conduct, and procedures for reporting incidents. Additionally, it should align with recognized open-source community standards, such as the Contributor Covenant, to ensure comprehensiveness and inclusivity.

Tasks:

Research and select an appropriate Code of Conduct template (e.g., Contributor Covenant, Citizen Code of Conduct).
Adapt the selected template to fit the specific needs and values of our community.
Create a new file named "CODE_OF_CONDUCT.md" or similar in the repository root directory.
Populate the file with the finalized Code of Conduct content.
Update the repository documentation and contributing guidelines to reference the Code of Conduct.
Communicate the implementation of the Code of Conduct to the community through appropriate channels (e.g., README.md, community forums, social media).

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/98798977/e21f60ed-99dc-4b69-a0e7-cf5a47ac3e4a)

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
