### ISSUE TITLE
[New Feature]: Create Issue_templated.md , Create Feature_template.md , Create Pull_Request_Template.md

### ISSUE THREAD

**Issue by hasmithagunda123** [GameSphere-MultiPlayer/PACKABUNCHAS#31]
### 🎮 feature Request

assign this to me under gssoc 

### Point down the features

create templates for easy navigation

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
