### ISSUE TITLE
[New Feature]: Adding light and dark themes.

### ISSUE THREAD

**Issue by Dhruv-Gaba** [GameSphere-MultiPlayer/PACKABUNCHAS#34]
### 🎮 feature Request

feature logic and basic description
The original theme of the game is too bright, i would like to add dark theme to the application.

![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/141745373/4f170625-2c79-4446-9a93-da6eb8f4c82c)

### Point down the features

feature points
Dark theme makes the game more user appealing.

please assign this issue to me.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Iisha10** [comment]
@Dhruv-Gaba i would like to work on this issue under GSSOC 2024.... Please assign this to me

**Comment by Durgesh4993** [comment]
@Dhruv-Gaba @Iisha10 Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
