### ISSUE TITLE
[New Feature]: Fixing the main page

### ISSUE THREAD

**Issue by YadlaMani** [GameSphere-MultiPlayer/PACKABUNCHAS#35]
### 🎮 feature Request

I would like to first add padding to make the elements more ordereded and also add title of the game and a git hub link to the repo and some good background to make the website better
![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/133841094/69fb0859-fb97-4bf7-b11c-e5722d73cd1b)

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by YadlaMani** [comment]
@Durgesh4993 @anshgautam-github pls assign me this issue under gssoc'24

**Comment by 143divya** [comment]
👋 Hi https://github.com/GameSphere-MultiPlayer,

I am Divyanjali developer(Core Team) Girlscript Summer of Code. I'll be collaborating with you on preparing your repo for GSSoC'24 Program

Why are these changes required?
After Analysing last year's contributions and feedback it would be great for students to have a couple of standard readme files on the repo to understand what the project is all about and some issues detailing what they can contribute. This will help you to see increased engagement in your repository as well.

As mentioned students get a chance to learn step by step, how to build this project as well as invite mentors to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for Girlscript summer of code 2024 on 10th May.

This issue will serve as a tracking issue to track all issues related to GSSoC'24. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch.

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated.

I look forward to working with you :octocat:

**Comment by Durgesh4993** [comment]
@YadlaMani Could you please explain more what you want to do, if possible you can also add screenshot....
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by YadlaMani** [comment]
![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/133841094/808d3d1b-c187-4e38-8d93-5076020fcc74)
i have rough idea of going with this layout and i am open to ideas and can do any ideas you suggest @Durgesh4993

**Comment by YadlaMani** [comment]
@Durgesh4993 sorry for the bad drawing

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
