### ISSUE TITLE
[Documentation Bug]: 

### ISSUE THREAD

**Issue by Dsmita03** [GameSphere-MultiPlayer/PACKABUNCHAS#37]
### Describe the bug ✍️

Update of README.md file is required.

### Provide step by step information reproduce the bug 📄

Description

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by 143divya** [comment]
GSSOC'24 contributor
Can You please assign this issue to me

**Comment by 143divya** [comment]
> ### Describe the bug ✍️
> I can update theREADME.md file  required.
> 
> ### Provide step by step information reproduce the bug 📄
> Description
> 
> ### Select program in which you are contributing
> GSSoC24
> 
> ### Code of Conduct
> * [x]  I follow CONTRIBUTING GUIDELINE of this project.

**Comment by Durgesh4993** [comment]
@Dsmita03 Could you please explain more what you want to do in Readme.md file......
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
