### ISSUE TITLE
Learn.md [Documentation Bug]: 

### ISSUE THREAD

**Issue by Meetjain1** [GameSphere-MultiPlayer/PACKABUNCHAS#38]
### Describe the bug ✍️

learn.md file is missing in our repository currently @Durgesh4993 sir assign this issue to me I will add it

I am working under gssoc24

### Provide step by step information reproduce the bug 📄

will add the file to the repository 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Meetjain1** [comment]
> If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...
> 
> Thank you :)

 Sure
