### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [GameSphere-MultiPlayer/PACKABUNCHAS#4]
### Describe the bug ✍️

 The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

### Provide step by step information reproduce the bug 📄

I need to create a CONTRIBUTING.md file tailored to our project's specific needs and guidelines. This file should include information on how to contribute, coding conventions, testing procedures, and any other relevant guidelines for potential contributors. By providing this information upfront, we can lower the barrier to entry for new contributors and ensure that contributions align with project standards.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/98798977/59228da1-e3b6-426d-9c85-9516c2782811)

**Comment by Durgesh4993** [comment]
But i think so we link of code of conduct and CONTRIBUTING GUIDELINE is not working

**Comment by Durgesh4993** [comment]
@suhanipaliwal Please raise any other issue, then i'll assign you 

If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
