### ISSUE TITLE
i want to improve in logo in title bar 

### ISSUE THREAD

**Issue by shuhaki** [GameSphere-MultiPlayer/PACKABUNCHAS#41]
### 🎮 feature Request

add acture logo in tiltle which are in first page

### Point down the features

logo

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shuhaki** [comment]
please assign me

**Comment by Durgesh4993** [comment]
@shuhaki Could you please explain more what you want to do, if possible you can also add screenshot....
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by HareRamDwivedi** [comment]
I am a GSSOC contributor please assign me this issue under GSSOC 2024
