### ISSUE TITLE
[New Feature]: Auto Commenting Feat for Issue Creation

### ISSUE THREAD

**Issue by Asymtode712** [GameSphere-MultiPlayer/PACKABUNCHAS#43]
### 🎮 feature Request

When issues are created in a project, it is important to provide immediate acknowledgment and guidance to the issue creator. However, manually commenting on every newly created issue can be time-consuming for maintainers, leading to delays and inconsistency in communication.
I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This comment could include acknowledgment of the issue, guidelines for further steps, or any other relevant information. The automation should be customizable to accommodate different project workflows and communication styles.

![issue creation](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/115717746/2f6de569-6792-4fce-aa9c-7d321b84033a)

### Point down the features

This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Asymtode712** [comment]
@Durgesh4993 please assign me this issue under gssoc'24

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
