### ISSUE TITLE
[New Feature]: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [GameSphere-MultiPlayer/PACKABUNCHAS#45]
### 🎮 feature Request

When pull requests (PRs) are merged in a project, it is often important to provide consistent feedback or notifications to the contributors. Currently, this process can be manual and time-consuming, leading to inconsistent communication and delayed acknowledgments. 

To enhance our communication and acknowledgment process, we're implementing an auto-commenting feature for specific events within our project repository. This feature will automatically generate comments under the following circumstances:
PR Merged: Upon the successful merging of a pull request (PR), an auto-comment will be added to the corresponding issue, indicating that the PR has been merged and expressing gratitude to the contributor for their valuable contribution.

![PR merged](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/115717746/819a7762-9184-49af-8690-0f256c3de0ff)

### Point down the features

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Asymtode712** [comment]
@Durgesh4993 please assign me this issue under gssoc'24

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
