### ISSUE TITLE
[New Feature]: Workflow for closing old PRs

### ISSUE THREAD

**Issue by Asymtode712** [GameSphere-MultiPlayer/PACKABUNCHAS#47]
### 🎮 feature Request

Over time, open pull requests (PRs) can accumulate in a repository, cluttering the interface and making it difficult to focus on active development tasks. Additionally, outdated or abandoned PRs may no longer serve their intended purpose and should be closed to maintain repository cleanliness.

Implement a workflow that automatically closes old PRs based on predefined criteria, such as their last update timestamp. By regularly closing PRs that have not been updated within a certain timeframe, the repository can stay organized, and contributors can focus on active and relevant PRs.

### Point down the features

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Asymtode712** [comment]
@Durgesh4993 please assign me this issue under gssoc'24

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
