### ISSUE TITLE
[New Feature]: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [GameSphere-MultiPlayer/PACKABUNCHAS#48]
### 🎮 feature Request

The solution is to automatically post a comment on the issue whenever it gets closed. This comment should thank the issue creator for their contribution and inform them that their issue has been closed. The message can include the issue number and a friendly greeting to make it more personal. This automation ensures that every closed issue receives a consistent and timely response, improving communication and contributor experience.

![issue closed](https://github.com/GameSphere-MultiPlayer/PACKABUNCHAS/assets/115717746/9bdd9921-4638-4867-8578-c792706ccbbe)

### Point down the features

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Asymtode712** [comment]
@Durgesh4993 please assign me this issue under gssoc'24

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
