### ISSUE TITLE
[New Feature]: Making the nav bar of the home page to sticky and add animations to the elements in nav bar while scrolling.

### ISSUE THREAD

**Issue by saiumasankar** [GameSphere-MultiPlayer/PACKABUNCHAS#53]
### 🎮 feature Request

I would like to make the nav bar fixed while scrolling and add animations to the elements in nav bar to highlight when we scroll through the website.

### Point down the features

feature points

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
